version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME : "kafka"
      KAFKA_CREATE_TOPICS: "input-topic:1:1,output-topic:1:1"
      KAFKA_ZOOKEEPER_CONNECT : zookeeper:2181

  kafka-to-kafka:
    image: bluehydrogen/kafkatokafka:latest
    depends_on:
      - kafka
      - zookeeper
    ports:
      - "8081:8081"